//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PapeD_Web.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SysUser", Namespace="http://schemas.datacontract.org/2004/07/PaperD_Service")]
    [System.SerializableAttribute()]
    public partial class SysUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RegistrationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegistrationDate {
            get {
                return this.RegistrationDateField;
            }
            set {
                if ((this.RegistrationDateField.Equals(value) != true)) {
                    this.RegistrationDateField = value;
                    this.RaisePropertyChanged("RegistrationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTypeField, value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/PaperD_Service")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProdCategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProdDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ProdDiscountPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProdIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProdImgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProdNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ProdPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProdQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProdStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProdCategory {
            get {
                return this.ProdCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdCategoryField, value) != true)) {
                    this.ProdCategoryField = value;
                    this.RaisePropertyChanged("ProdCategory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProdDescription {
            get {
                return this.ProdDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdDescriptionField, value) != true)) {
                    this.ProdDescriptionField = value;
                    this.RaisePropertyChanged("ProdDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ProdDiscountPrice {
            get {
                return this.ProdDiscountPriceField;
            }
            set {
                if ((this.ProdDiscountPriceField.Equals(value) != true)) {
                    this.ProdDiscountPriceField = value;
                    this.RaisePropertyChanged("ProdDiscountPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProdId {
            get {
                return this.ProdIdField;
            }
            set {
                if ((this.ProdIdField.Equals(value) != true)) {
                    this.ProdIdField = value;
                    this.RaisePropertyChanged("ProdId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProdImg {
            get {
                return this.ProdImgField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdImgField, value) != true)) {
                    this.ProdImgField = value;
                    this.RaisePropertyChanged("ProdImg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProdName {
            get {
                return this.ProdNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdNameField, value) != true)) {
                    this.ProdNameField = value;
                    this.RaisePropertyChanged("ProdName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ProdPrice {
            get {
                return this.ProdPriceField;
            }
            set {
                if ((this.ProdPriceField.Equals(value) != true)) {
                    this.ProdPriceField = value;
                    this.RaisePropertyChanged("ProdPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProdQuantity {
            get {
                return this.ProdQuantityField;
            }
            set {
                if ((this.ProdQuantityField.Equals(value) != true)) {
                    this.ProdQuantityField = value;
                    this.RaisePropertyChanged("ProdQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProdStatus {
            get {
                return this.ProdStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdStatusField, value) != true)) {
                    this.ProdStatusField = value;
                    this.RaisePropertyChanged("ProdStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProdReview", Namespace="http://schemas.datacontract.org/2004/07/PaperD_Service")]
    [System.SerializableAttribute()]
    public partial class ProdReview : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProdIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RevDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RevIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RevStarsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReviewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProdId {
            get {
                return this.ProdIdField;
            }
            set {
                if ((this.ProdIdField.Equals(value) != true)) {
                    this.ProdIdField = value;
                    this.RaisePropertyChanged("ProdId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RevDate {
            get {
                return this.RevDateField;
            }
            set {
                if ((this.RevDateField.Equals(value) != true)) {
                    this.RevDateField = value;
                    this.RaisePropertyChanged("RevDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RevId {
            get {
                return this.RevIdField;
            }
            set {
                if ((this.RevIdField.Equals(value) != true)) {
                    this.RevIdField = value;
                    this.RaisePropertyChanged("RevId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RevStars {
            get {
                return this.RevStarsField;
            }
            set {
                if ((this.RevStarsField.Equals(value) != true)) {
                    this.RevStarsField = value;
                    this.RaisePropertyChanged("RevStars");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Review {
            get {
                return this.ReviewField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewField, value) != true)) {
                    this.ReviewField = value;
                    this.RaisePropertyChanged("Review");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPaperD")]
    public interface IPaperD {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaperD/Login", ReplyAction="http://tempuri.org/IPaperD/LoginResponse")]
        PapeD_Web.ServiceReference1.SysUser Login(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaperD/Login", ReplyAction="http://tempuri.org/IPaperD/LoginResponse")]
        System.Threading.Tasks.Task<PapeD_Web.ServiceReference1.SysUser> LoginAsync(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaperD/RegisterUser", ReplyAction="http://tempuri.org/IPaperD/RegisterUserResponse")]
        bool RegisterUser(string name, string email, string HashedPass, string usertype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaperD/RegisterUser", ReplyAction="http://tempuri.org/IPaperD/RegisterUserResponse")]
        System.Threading.Tasks.Task<bool> RegisterUserAsync(string name, string email, string HashedPass, string usertype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaperD/getProductsByStatus", ReplyAction="http://tempuri.org/IPaperD/getProductsByStatusResponse")]
        PapeD_Web.ServiceReference1.Product[] getProductsByStatus(string ProdStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaperD/getProductsByStatus", ReplyAction="http://tempuri.org/IPaperD/getProductsByStatusResponse")]
        System.Threading.Tasks.Task<PapeD_Web.ServiceReference1.Product[]> getProductsByStatusAsync(string ProdStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaperD/GetProduct", ReplyAction="http://tempuri.org/IPaperD/GetProductResponse")]
        PapeD_Web.ServiceReference1.Product GetProduct(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaperD/GetProduct", ReplyAction="http://tempuri.org/IPaperD/GetProductResponse")]
        System.Threading.Tasks.Task<PapeD_Web.ServiceReference1.Product> GetProductAsync(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaperD/addProduct", ReplyAction="http://tempuri.org/IPaperD/addProductResponse")]
        bool addProduct(int prodId, string name, string description, int quantity, decimal price, string status, string image, string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaperD/addProduct", ReplyAction="http://tempuri.org/IPaperD/addProductResponse")]
        System.Threading.Tasks.Task<bool> addProductAsync(int prodId, string name, string description, int quantity, decimal price, string status, string image, string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaperD/addReview", ReplyAction="http://tempuri.org/IPaperD/addReviewResponse")]
        bool addReview(int prodId, int userId, int stars, string review);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaperD/addReview", ReplyAction="http://tempuri.org/IPaperD/addReviewResponse")]
        System.Threading.Tasks.Task<bool> addReviewAsync(int prodId, int userId, int stars, string review);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaperD/EditReview", ReplyAction="http://tempuri.org/IPaperD/EditReviewResponse")]
        bool EditReview(int revId, int stars, string review);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaperD/EditReview", ReplyAction="http://tempuri.org/IPaperD/EditReviewResponse")]
        System.Threading.Tasks.Task<bool> EditReviewAsync(int revId, int stars, string review);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaperD/retrievReview", ReplyAction="http://tempuri.org/IPaperD/retrievReviewResponse")]
        PapeD_Web.ServiceReference1.ProdReview retrievReview(int userid, int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaperD/retrievReview", ReplyAction="http://tempuri.org/IPaperD/retrievReviewResponse")]
        System.Threading.Tasks.Task<PapeD_Web.ServiceReference1.ProdReview> retrievReviewAsync(int userid, int productId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPaperDChannel : PapeD_Web.ServiceReference1.IPaperD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaperDClient : System.ServiceModel.ClientBase<PapeD_Web.ServiceReference1.IPaperD>, PapeD_Web.ServiceReference1.IPaperD {
        
        public PaperDClient() {
        }
        
        public PaperDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaperDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaperDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaperDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PapeD_Web.ServiceReference1.SysUser Login(string Email, string Password) {
            return base.Channel.Login(Email, Password);
        }
        
        public System.Threading.Tasks.Task<PapeD_Web.ServiceReference1.SysUser> LoginAsync(string Email, string Password) {
            return base.Channel.LoginAsync(Email, Password);
        }
        
        public bool RegisterUser(string name, string email, string HashedPass, string usertype) {
            return base.Channel.RegisterUser(name, email, HashedPass, usertype);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterUserAsync(string name, string email, string HashedPass, string usertype) {
            return base.Channel.RegisterUserAsync(name, email, HashedPass, usertype);
        }
        
        public PapeD_Web.ServiceReference1.Product[] getProductsByStatus(string ProdStatus) {
            return base.Channel.getProductsByStatus(ProdStatus);
        }
        
        public System.Threading.Tasks.Task<PapeD_Web.ServiceReference1.Product[]> getProductsByStatusAsync(string ProdStatus) {
            return base.Channel.getProductsByStatusAsync(ProdStatus);
        }
        
        public PapeD_Web.ServiceReference1.Product GetProduct(int productId) {
            return base.Channel.GetProduct(productId);
        }
        
        public System.Threading.Tasks.Task<PapeD_Web.ServiceReference1.Product> GetProductAsync(int productId) {
            return base.Channel.GetProductAsync(productId);
        }
        
        public bool addProduct(int prodId, string name, string description, int quantity, decimal price, string status, string image, string category) {
            return base.Channel.addProduct(prodId, name, description, quantity, price, status, image, category);
        }
        
        public System.Threading.Tasks.Task<bool> addProductAsync(int prodId, string name, string description, int quantity, decimal price, string status, string image, string category) {
            return base.Channel.addProductAsync(prodId, name, description, quantity, price, status, image, category);
        }
        
        public bool addReview(int prodId, int userId, int stars, string review) {
            return base.Channel.addReview(prodId, userId, stars, review);
        }
        
        public System.Threading.Tasks.Task<bool> addReviewAsync(int prodId, int userId, int stars, string review) {
            return base.Channel.addReviewAsync(prodId, userId, stars, review);
        }
        
        public bool EditReview(int revId, int stars, string review) {
            return base.Channel.EditReview(revId, stars, review);
        }
        
        public System.Threading.Tasks.Task<bool> EditReviewAsync(int revId, int stars, string review) {
            return base.Channel.EditReviewAsync(revId, stars, review);
        }
        
        public PapeD_Web.ServiceReference1.ProdReview retrievReview(int userid, int productId) {
            return base.Channel.retrievReview(userid, productId);
        }
        
        public System.Threading.Tasks.Task<PapeD_Web.ServiceReference1.ProdReview> retrievReviewAsync(int userid, int productId) {
            return base.Channel.retrievReviewAsync(userid, productId);
        }
    }
}
